-- Hand-written migration: no live DATABASE_URL was available in the
-- session that authored this, so this was NOT generated by
-- `prisma migrate dev` and has NOT been applied or tested against any
-- database. Before running this against a real database:
--   1. Confirm the existing "feedback" table is actually named "feedback"
--      (it is, per the @@map("feedback") in prisma/schema.prisma) and that
--      no column named "rating" or "vibeTags" already exists there.
--   2. Ideally, regenerate this migration for real via
--      `prisma migrate dev` once DATABASE_URL is available, and use
--      this file only as a reviewed starting point/reference.
--   3. Follow this project's own precedent for schema changes:
--      docs/references/THEME_MODEL_MIGRATION_GUIDE.md (backup -> seed
--      reference data -> backfill -> migrate -> verify -> documented
--      rollback). Nothing in this migration requires a backfill - both
--      new columns are additive ("rating" is nullable, "vibeTags" defaults
--      to an empty array) so every existing row remains valid with no
--      data movement - but take a backup first regardless.
--
-- Context: packages/db/src/repositories/feedback.repository.ts already has
-- a getAverageRatingForRestaurant() method (added by a different agent in
-- an earlier dispatch, before this column existed) that references
-- "f.rating" via $queryRaw wrapped in a try/catch specifically because this
-- column didn't exist yet. Once this migration is applied, that method
-- starts working correctly at runtime - no code changes needed there.

-- AlterTable
ALTER TABLE "feedback" ADD COLUMN "rating" INTEGER;
ALTER TABLE "feedback" ADD COLUMN "vibeTags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
