// Action definitions for RBAC
export enum Action {
  // User actions
  VIEW_PROFILE = "VIEW_PROFILE",
  EDIT_PROFILE = "EDIT_PROFILE",
  DELETE_ACCOUNT = "DELETE_ACCOUNT",

  // Dinner actions
  CREATE_DINNER = "CREATE_DINNER",
  EDIT_DINNER = "EDIT_DINNER",
  DELETE_DINNER = "DELETE_DINNER",
  JOIN_DINNER = "JOIN_DINNER",
  LEAVE_DINNER = "LEAVE_DINNER",

  // Restaurant actions
  CREATE_RESTAURANT = "CREATE_RESTAURANT",
  EDIT_RESTAURANT = "EDIT_RESTAURANT",
  DELETE_RESTAURANT = "DELETE_RESTAURANT",
  VIEW_RESTAURANT_ANALYTICS = "VIEW_RESTAURANT_ANALYTICS",

  // Platform admin actions
  VIEW_ADMIN_PANEL = "VIEW_ADMIN_PANEL",
  MANAGE_USERS = "MANAGE_USERS",
  MANAGE_RESTAURANTS = "MANAGE_RESTAURANTS",
  VIEW_PLATFORM_ANALYTICS = "VIEW_PLATFORM_ANALYTICS",
  ASSIGN_ROLES = "ASSIGN_ROLES",
}
