-- Hand-written migration: no live DATABASE_URL was available in the
-- session that authored this, so this was NOT generated by
-- `prisma migrate dev` and has NOT been applied or tested against any
-- database. Before running this against a real database:
--   1. Run `prisma db pull` (or inspect the live schema directly) and
--      confirm the existing "feedback" table's target-user foreign key
--      is actually named "feedback_targetUserId_fkey" (the assumption
--      below follows Prisma's default naming convention, but this
--      repository's earliest tables were never captured in a tracked
--      migration file - only "add_restaurant_models" and
--      "add_restaurant_media" exist in prisma/migrations/ - so this
--      convention could not be verified against migration history).
--      If the name differs, fix the DROP/ADD CONSTRAINT statements below.
--   2. Ideally, regenerate this migration for real via
--      `prisma migrate dev` once DATABASE_URL is available, and use
--      this file only as a reviewed starting point/reference.
--   3. Follow this project's own precedent for schema changes:
--      docs/references/THEME_MODEL_MIGRATION_GUIDE.md (backup -> seed
--      reference data -> backfill -> migrate -> verify -> documented
--      rollback). Nothing in this migration requires a backfill (every
--      new column is nullable and every new table starts empty), but
--      take a backup first regardless.

-- ============================================================
-- Step 1: New, purely additive tables (zero backfill risk)
-- ============================================================

-- CreateEnum
CREATE TYPE "MenuCourse" AS ENUM ('STARTER', 'MAIN', 'DESSERT');

-- CreateTable
CREATE TABLE "menu_items" (
    "id" TEXT NOT NULL,
    "restaurantId" TEXT NOT NULL,
    "course" "MenuCourse" NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "priceCents" INTEGER NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "isAvailable" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "menu_items_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "menu_items_restaurantId_idx" ON "menu_items"("restaurantId");

-- CreateIndex
CREATE INDEX "menu_items_restaurantId_course_idx" ON "menu_items"("restaurantId", "course");

-- AddForeignKey
ALTER TABLE "menu_items" ADD CONSTRAINT "menu_items_restaurantId_fkey" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- CreateEnum
CREATE TYPE "ComplianceDocType" AS ENUM ('BUSINESS_REGISTRATION', 'FOOD_SAFETY_CERTIFICATE', 'LIQUOR_LICENSE', 'OTHER');

-- CreateTable
CREATE TABLE "compliance_documents" (
    "id" TEXT NOT NULL,
    "restaurantId" TEXT NOT NULL,
    "docType" "ComplianceDocType" NOT NULL,
    "fileName" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "verifiedAt" TIMESTAMP(3),
    "verifiedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "compliance_documents_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "compliance_documents_restaurantId_idx" ON "compliance_documents"("restaurantId");

-- CreateIndex
CREATE INDEX "compliance_documents_restaurantId_docType_idx" ON "compliance_documents"("restaurantId", "docType");

-- AddForeignKey
ALTER TABLE "compliance_documents" ADD CONSTRAINT "compliance_documents_restaurantId_fkey" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "compliance_documents" ADD CONSTRAINT "compliance_documents_verifiedById_fkey" FOREIGN KEY ("verifiedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- CreateTable
CREATE TABLE "recurring_dinner_series" (
    "id" TEXT NOT NULL,
    "restaurantId" TEXT NOT NULL,
    "themeId" TEXT NOT NULL,
    "dayOfWeek" INTEGER NOT NULL,
    "startTime" TEXT NOT NULL,
    "endTime" TEXT NOT NULL,
    "seatCount" INTEGER NOT NULL,
    "pricePerSeatCents" INTEGER,
    "description" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "recurring_dinner_series_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "recurring_dinner_series_restaurantId_idx" ON "recurring_dinner_series"("restaurantId");

-- CreateIndex
CREATE INDEX "recurring_dinner_series_isActive_idx" ON "recurring_dinner_series"("isActive");

-- AddForeignKey
ALTER TABLE "recurring_dinner_series" ADD CONSTRAINT "recurring_dinner_series_restaurantId_fkey" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "recurring_dinner_series" ADD CONSTRAINT "recurring_dinner_series_themeId_fkey" FOREIGN KEY ("themeId") REFERENCES "themes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- CreateTable
CREATE TABLE "restaurant_tables" (
    "id" TEXT NOT NULL,
    "restaurantId" TEXT NOT NULL,
    "capacity" INTEGER NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "restaurant_tables_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "restaurant_tables_restaurantId_idx" ON "restaurant_tables"("restaurantId");

-- AddForeignKey
ALTER TABLE "restaurant_tables" ADD CONSTRAINT "restaurant_tables_restaurantId_fkey" FOREIGN KEY ("restaurantId") REFERENCES "restaurants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ============================================================
-- Step 2: SafetyReport + its 3 new User relations (also additive,
-- kept as its own labeled step for a cleaner diff per the migration
-- plan's recommended sequence, even though it's one file here)
-- ============================================================

-- CreateEnum
CREATE TYPE "SafetyReportReason" AS ENUM ('MADE_UNCOMFORTABLE', 'INAPPROPRIATE_BEHAVIOR', 'SAFETY_CONCERN', 'OTHER');

-- CreateEnum
CREATE TYPE "SafetyReportStatus" AS ENUM ('PENDING', 'REVIEWED', 'ACTIONED', 'DISMISSED');

-- CreateTable
CREATE TABLE "safety_reports" (
    "id" TEXT NOT NULL,
    "reporterId" TEXT NOT NULL,
    "reportedUserId" TEXT,
    "dinnerId" TEXT,
    "reason" "SafetyReportReason" NOT NULL,
    "reasonDetail" TEXT,
    "status" "SafetyReportStatus" NOT NULL DEFAULT 'PENDING',
    "resolution" TEXT,
    "reviewedById" TEXT,
    "reviewedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "safety_reports_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "safety_reports_reporterId_idx" ON "safety_reports"("reporterId");

-- CreateIndex
CREATE INDEX "safety_reports_reportedUserId_idx" ON "safety_reports"("reportedUserId");

-- CreateIndex
CREATE INDEX "safety_reports_dinnerId_idx" ON "safety_reports"("dinnerId");

-- CreateIndex
CREATE INDEX "safety_reports_status_idx" ON "safety_reports"("status");

-- CreateIndex
CREATE INDEX "safety_reports_reason_idx" ON "safety_reports"("reason");

-- CreateIndex
CREATE INDEX "safety_reports_createdAt_idx" ON "safety_reports"("createdAt");

-- AddForeignKey
ALTER TABLE "safety_reports" ADD CONSTRAINT "safety_reports_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_reports" ADD CONSTRAINT "safety_reports_reportedUserId_fkey" FOREIGN KEY ("reportedUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_reports" ADD CONSTRAINT "safety_reports_dinnerId_fkey" FOREIGN KEY ("dinnerId") REFERENCES "dinners"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_reports" ADD CONSTRAINT "safety_reports_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================
-- Step 3: Restaurant.defaultPricePerSeatCents, Dinner.pricePerSeatCents
-- + Dinner.seriesId. Nullable, no backfill needed - but see the
-- migration plan's own warning: introducing a real per-dinner price
-- is coupled to an application-code change in
-- packages/config/src/payment.ts (getCommitmentAmount currently
-- ignores the dinner entirely and returns a flat R50 for every
-- booking). Adding these columns alone does not make prices real;
-- ship them together with that code change, not as a schema-only step.
-- ============================================================

-- AlterTable
ALTER TABLE "restaurants" ADD COLUMN "defaultPricePerSeatCents" INTEGER;

-- AlterTable
ALTER TABLE "dinners" ADD COLUMN "pricePerSeatCents" INTEGER,
ADD COLUMN "seriesId" TEXT;

-- CreateIndex
CREATE INDEX "dinners_seriesId_idx" ON "dinners"("seriesId");

-- AddForeignKey
ALTER TABLE "dinners" ADD CONSTRAINT "dinners_seriesId_fkey" FOREIGN KEY ("seriesId") REFERENCES "recurring_dinner_series"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================
-- Step 4: Feedback.targetUserId cascade-delete bugfix (see the
-- migration plan's §05: the field's own comment says "Null for
-- table-level feedback," but the relation was declared onDelete:
-- Cascade, so deleting a targeted user was deleting the feedback that
-- named them instead of nulling the target - losing data that should
-- survive account deletion). VERIFY the constraint name below against
-- the live database before running - see the warning at the top of
-- this file.
-- ============================================================

-- DropForeignKey
ALTER TABLE "feedback" DROP CONSTRAINT "feedback_targetUserId_fkey";

-- AddForeignKey
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_targetUserId_fkey" FOREIGN KEY ("targetUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
