import { prisma } from "../client";
import { UserRepository } from "./user.repository";
import { RestaurantRepository } from "./restaurant.repository";
import { MediaRepository } from "./media.repository";
import { DinnerRepository } from "./dinner.repository";
import { SeatRepository } from "./seat.repository";
import { AuditLogRepository } from "./audit-log.repository";
import { TrustEventRepository } from "./trust-event.repository";
import { FeedbackRepository } from "./feedback.repository";
import { MutualInterestRepository } from "./mutual-interest.repository";
import { TrustProfileRepository } from "./trust-profile.repository";
import { ThemeRepository } from "./theme.repository";
import { AnalyticsRepository } from "./analytics.repository";
import { PaymentIntentRepository } from "./payment-intent.repository";
import { SafetyReportRepository } from "./safety-report.repository";
import { MenuItemRepository } from "./menu-item.repository";
import { ComplianceDocumentRepository } from "./compliance-document.repository";

export const userRepository = new UserRepository(prisma);
export const restaurantRepository = new RestaurantRepository(prisma);
export const mediaRepository = new MediaRepository(prisma);
export const dinnerRepository = new DinnerRepository(prisma);
export const seatRepository = new SeatRepository(prisma);
export const auditLogRepository = new AuditLogRepository(prisma);
export const trustEventRepository = new TrustEventRepository(prisma);
export const feedbackRepository = new FeedbackRepository(prisma);
export const mutualInterestRepository = new MutualInterestRepository(prisma);
export const trustProfileRepository = new TrustProfileRepository(prisma);
export const themeRepository = new ThemeRepository(prisma);
export const analyticsRepository = new AnalyticsRepository(prisma);
export const paymentIntentRepository = new PaymentIntentRepository(prisma);
export const safetyReportRepository = new SafetyReportRepository(prisma);
export const menuItemRepository = new MenuItemRepository(prisma);
export const complianceDocumentRepository = new ComplianceDocumentRepository(prisma);

export { BaseRepository } from "./base";
export { UserRepository } from "./user.repository";
export { RestaurantRepository } from "./restaurant.repository";
export { MediaRepository } from "./media.repository";
export { DinnerRepository } from "./dinner.repository";
export { SeatRepository } from "./seat.repository";
export { AuditLogRepository } from "./audit-log.repository";
export { TrustEventRepository } from "./trust-event.repository";
export { FeedbackRepository } from "./feedback.repository";
export { MutualInterestRepository } from "./mutual-interest.repository";
export { TrustProfileRepository } from "./trust-profile.repository";
export { ThemeRepository } from "./theme.repository";
export { AnalyticsRepository } from "./analytics.repository";
export { PaymentIntentRepository } from "./payment-intent.repository";
export { SafetyReportRepository } from "./safety-report.repository";
export { MenuItemRepository } from "./menu-item.repository";
export { ComplianceDocumentRepository } from "./compliance-document.repository";
export type { RestaurantWithMembers, RestaurantCreateData, RestaurantWithMedia } from "./restaurant.repository";
export type { DinnerWithRestaurant } from "./dinner.repository";
export type { AuditLogWithActor } from "./audit-log.repository";
export type { FeedbackWithRelations } from "./feedback.repository";
export type { MutualInterestWithRelations } from "./mutual-interest.repository";
export type { ThemeAnalytics } from "./analytics.repository";
export type { PaymentIntentWithRelations } from "./payment-intent.repository";
export type { SafetyReportWithRelations } from "./safety-report.repository";
